-- ============================================================================
-- BJCL_DB: Complete PostgreSQL 18 Database Initialization Script
-- System: Bally Jute Company Limited (BJL) - Raw Jute Management System
-- Database: bjcl_db
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
SET timezone = 'Asia/Kolkata';

-- Master Tables
CREATE TABLE IF NOT EXISTS financial_year_master (
    year_code TEXT PRIMARY KEY,
    start_date DATE,
    end_date DATE,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS area_master (
    area_code TEXT PRIMARY KEY,
    area_name TEXT NOT NULL,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS agency_master (
    agency_code TEXT PRIMARY KEY,
    area_code TEXT,
    agency_name TEXT NOT NULL,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS grade_master (
    grade_code TEXT PRIMARY KEY,
    grade_name TEXT NOT NULL,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS godown_master (
    gdn_code TEXT PRIMARY KEY,
    gdn_name TEXT NOT NULL,
    gdn_capacity NUMERIC(15,2),
    gdn_short_name TEXT,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS supply_master (
    supp_code TEXT PRIMARY KEY,
    supp_name TEXT NOT NULL,
    acc_no TEXT,
    supp_add1 TEXT,
    supp_add2 TEXT,
    supp_add3 TEXT,
    supp_city TEXT,
    supp_contact TEXT,
    supp_ph_no TEXT,
    supp_cell_no TEXT,
    supp_fax_no TEXT,
    supp_email TEXT,
    supp_webadd TEXT,
    erp_user_code TEXT,
    pan_no TEXT,
    ifsc_code TEXT,
    ifsc_branch TEXT,
    supplier_group TEXT,
    jc_regis_no TEXT,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS broker_master (
    brok_code TEXT PRIMARY KEY,
    brok_name TEXT NOT NULL,
    acc_no TEXT,
    brok_add1 TEXT,
    brok_add2 TEXT,
    brok_add3 TEXT,
    brok_city TEXT,
    brok_contact TEXT,
    brok_ph_no TEXT,
    brok_cell_no TEXT,
    brok_fax_no TEXT,
    brok_email TEXT,
    brok_webadd TEXT,
    broker_group TEXT,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS unit_master (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    unit_name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS user_master (
    user_id TEXT PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password TEXT,
    password_hash TEXT,
    role TEXT DEFAULT 'operator',
    status TEXT DEFAULT 'Active',
    email TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    last_login TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS authentication_master (
    auth_id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    user_id TEXT,
    portal_access JSONB,
    role_type TEXT,
    last_login TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Transaction Tables
CREATE TABLE IF NOT EXISTS sauda_master (
    sauda_id TEXT PRIMARY KEY,
    financial_year TEXT NOT NULL,
    sauda_no TEXT NOT NULL,
    session TEXT, 
    po_type TEXT,
    date DATE,
    broker TEXT,
    supplier TEXT,
    challan_supplier TEXT,
    area TEXT,
    agency TEXT,
    marks TEXT,
    no_of_lorries INTEGER,
    units_per_lorry NUMERIC(15,2),
    units_per_lorry_type TEXT,
    total_unit INTEGER,
    wt_per_lorry NUMERIC(15,3),
    unit_type TEXT,
    total_wt_in_ton NUMERIC(15,3),
    shipment_date DATE,
    shipment_days INTEGER,
    shipment_penalty NUMERIC(15,2),
    marks_claim NUMERIC(15,2),
    quantity_claim NUMERIC(15,2),
    remarks TEXT,
    b_rate NUMERIC(15,2),
    b_date DATE,
    superior_normal_marks TEXT,
    signature_url TEXT,
    status TEXT DEFAULT 'pending',
    open_remarks JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS sauda_quality_details (
    detail_id TEXT PRIMARY KEY,
    sauda_id TEXT,
    financial_year TEXT,
    quality TEXT,
    qty NUMERIC(15,3),
    rs NUMERIC(15,2),
    agency TEXT,
    marka TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS sauda_check_point (
    po_id TEXT PRIMARY KEY,
    financial_year TEXT,
    purchase_order TEXT,
    po_type TEXT,
    ptf_no TEXT,
    pending BOOLEAN DEFAULT TRUE,
    po_no TEXT NOT NULL,
    po_date DATE,
    broker TEXT,
    supplier TEXT,
    challan_supplier TEXT,
    area TEXT,
    trans_paid_by TEXT,
    weight_unit_kgs NUMERIC(15,2),
    against_cancellation TEXT,
    purchase_unit_code TEXT,
    purchase_unit_name TEXT,
    total_lorries NUMERIC(15,2),
    units_per_lorry NUMERIC(15,2),
    total_units NUMERIC(15,2),
    weight_per_lorry NUMERIC(15,3),
    total_contract_mt NUMERIC(15,3),
    marka_type TEXT,
    marka_penalty NUMERIC(15,2),
    qty_penalty NUMERIC(15,2),
    delivery_from DATE,
    delivery_to DATE,
    grace_days INTEGER,
    delivery_penalty NUMERIC(15,2),
    contract_po_no TEXT,
    contract_date DATE,
    rate_detail TEXT,
    delivery_schedule TEXT,
    terms_condition TEXT,
    remarks TEXT,
    po_identification TEXT,
    b_rate NUMERIC(15,2),
    s_date DATE,
    status TEXT DEFAULT 'pending',
    open_remarks JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS sauda_check_point_details (
    item_id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    po_no TEXT,
    srl_no INTEGER,
    crop_year TEXT,
    grade_code TEXT,
    agency_code TEXT,
    marka_code TEXT,
    quantity INTEGER,
    weight_mt NUMERIC(15,3),
    rate_qntl NUMERIC(15,2),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS sauda_check_point_deductions (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    po_no TEXT,
    deduction_type TEXT,
    rate NUMERIC(15,2),
    qty NUMERIC(15,2),
    amount NUMERIC(15,2),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS satta_base_rates (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    rate_date DATE,
    variety TEXT,
    crop_year TEXT,
    base_rate NUMERIC(15,2),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS satta_differentials (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    rate_date DATE,
    variety TEXT,
    crop_year TEXT,
    from_grade TEXT,
    to_grade TEXT,
    differential_amount NUMERIC(15,2),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS satta_calculated_rates (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    rate_date DATE,
    variety TEXT,
    crop_year TEXT,
    grade TEXT,
    agency TEXT,
    calculated_rate NUMERIC(15,2),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS purchase_master (
    po_id TEXT PRIMARY KEY,
    financial_year TEXT,
    purchase_order TEXT,
    po_type TEXT,
    ptf_no TEXT,
    pending BOOLEAN DEFAULT TRUE,
    po_no TEXT NOT NULL,
    po_date DATE,
    broker TEXT,
    supplier TEXT,
    challan_supplier TEXT,
    area TEXT,
    trans_paid_by TEXT,
    weight_unit_kgs NUMERIC(15,2),
    against_cancellation TEXT,
    purchase_unit_code TEXT,
    purchase_unit_name TEXT,
    total_lorries NUMERIC(15,2),
    units_per_lorry NUMERIC(15,2),
    total_units NUMERIC(15,2),
    weight_per_lorry NUMERIC(15,3),
    total_contract_mt NUMERIC(15,3),
    marka_type TEXT,
    marka_penalty NUMERIC(15,2),
    qty_penalty NUMERIC(15,2),
    delivery_from DATE,
    delivery_to DATE,
    grace_days INTEGER,
    delivery_penalty NUMERIC(15,2),
    contract_po_no TEXT,
    contract_date DATE,
    rate_detail TEXT,
    delivery_schedule TEXT,
    terms_condition TEXT,
    remarks TEXT,
    po_identification TEXT,
    b_rate NUMERIC(15,2),
    s_date DATE,
    status TEXT DEFAULT 'pending',
    open_remarks JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS purchase_detail_master (
    item_id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    po_no TEXT,
    srl_no INTEGER,
    crop_year TEXT,
    grade_code TEXT,
    agency_code TEXT,
    marka_code TEXT,
    quantity INTEGER,
    weight_mt NUMERIC(15,3),
    rate_qntl NUMERIC(15,2),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS temporary_material_received (
    amad_id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    financial_year TEXT,
    temporary_arrival_no TEXT,
    temporary_arrival_date DATE,
    po_no TEXT,
    po_date DATE,
    jci TEXT,
    jci_no TEXT,
    supplier TEXT,
    challan_supplier TEXT,
    broker TEXT,
    transporter_name TEXT,
    lorry_number TEXT,
    lorry_date DATE,
    pan_no TEXT,
    part_no TEXT,
    part_date DATE,
    di_no TEXT,
    di_date DATE,
    challan_railway_receipt_no TEXT,
    challan_rr_no TEXT,
    challan_rr_date DATE,
    invoice_no TEXT,
    invoice_date DATE,
    consignment_note TEXT,
    consignment_note_no TEXT,
    consignment_note_date DATE,
    arrival_area_code TEXT,
    arrival_area_name TEXT,
    arrival_area TEXT,
    area TEXT,
    ptf TEXT,
    rfs TEXT,
    lorry_returned TEXT,
    lorry_returned_other_mill TEXT,
    way_bill_no TEXT,
    way_bill_date DATE,
    rr_gr_no TEXT,
    unit_name TEXT,
    total_packets INTEGER DEFAULT 0,
    grid_details JSONB,
    details JSONB,
    items JSONB,
    status TEXT DEFAULT 'Pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS final_arrival (
    final_arrival_id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    id TEXT,
    financial_year TEXT,
    final_arrival_no TEXT,
    arrival_no TEXT,
    temporary_arrival_no TEXT,
    temporary_arrival_date DATE,
    final_arrival_date DATE,
    mr_no TEXT,
    mr_date DATE,
    date DATE,
    po_no TEXT,
    po_date DATE,
    jci TEXT,
    jci_no TEXT,
    supplier TEXT,
    challan_supplier TEXT,
    broker TEXT,
    transporter_name TEXT,
    lorry_number TEXT,
    lorry_date DATE,
    pan_no TEXT,
    part_no TEXT,
    part_date DATE,
    di_no TEXT,
    di_date DATE,
    challan_railway_receipt_no TEXT,
    challan_rr_no TEXT,
    challan_rr_date DATE,
    invoice_no TEXT,
    invoice_date DATE,
    consignment_note TEXT,
    consignment_note_no TEXT,
    consignment_note_date DATE,
    arrival_area_code TEXT,
    arrival_area_name TEXT,
    arrival_area TEXT,
    area TEXT,
    ptf TEXT,
    rfs TEXT,
    lorry_returned TEXT,
    lorry_returned_other_mill TEXT,
    way_bill_no TEXT,
    way_bill_date DATE,
    rr_gr_no TEXT,
    unit_name TEXT,
    total_packets INTEGER DEFAULT 0,
    grid_details JSONB,
    details JSONB,
    items JSONB,
    status TEXT DEFAULT 'Completed',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS inspection_master (
    mr_no TEXT PRIMARY KEY,
    mr_date DATE,
    date DATE,
    arrival_no TEXT,
    arrival_date DATE,
    po_no TEXT,
    po_date DATE,
    broker_name TEXT,
    supplier_name TEXT,
    arrival_area_code TEXT,
    arrival_area_name TEXT,
    arrival_area TEXT,
    grid_details JSONB,
    actual_moisture NUMERIC,
    claim_moisture NUMERIC,
    actual_dust NUMERIC,
    claim_dust NUMERIC,
    actual_ncv NUMERIC,
    claim_ncv NUMERIC,
    detention_days NUMERIC,
    unloading_date DATE,
    mill_po_no TEXT,
    mill_po_date DATE,
    mr_spcl_print TEXT,
    remarks TEXT,
    lorry_number TEXT,
    delivery_claim NUMERIC DEFAULT 0,
    deduction_type TEXT,
    deduction_rate NUMERIC DEFAULT 0,
    deduction_qty NUMERIC DEFAULT 0,
    deduction_amount NUMERIC DEFAULT 0,
    status TEXT DEFAULT 'Completed',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    arival_apmc_fees NUMERIC DEFAULT 0
);

CREATE TABLE IF NOT EXISTS inspection_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mr_no TEXT,
    srl_no INTEGER,
    arrival_grade TEXT,
    stock_grade_code TEXT,
    stock_grade_name TEXT,
    area TEXT,
    agency TEXT,
    marka TEXT,
    marks TEXT,
    crop_year TEXT,
    lot TEXT,
    quantity NUMERIC DEFAULT 0,
    unit TEXT DEFAULT 'BALES',
    challan_gross_wt NUMERIC DEFAULT 0,
    receipt_gross_wt NUMERIC DEFAULT 0,
    gross_weight_batch NUMERIC DEFAULT 0,
    add_weight NUMERIC DEFAULT 0,
    less_weight NUMERIC DEFAULT 0,
    reduced_weight NUMERIC DEFAULT 0,
    lorry_moisture_min NUMERIC DEFAULT 0,
    lorry_moisture_max NUMERIC DEFAULT 0,
    lorry_read_min NUMERIC DEFAULT 0,
    lorry_read_max NUMERIC DEFAULT 0,
    lorry_read_avg NUMERIC DEFAULT 0,
    insp_read_min NUMERIC DEFAULT 0,
    insp_read_max NUMERIC DEFAULT 0,
    insp_read_avg NUMERIC DEFAULT 0,
    moisture_act NUMERIC DEFAULT 0,
    moisture_claim NUMERIC DEFAULT 0,
    dust_act NUMERIC DEFAULT 0,
    dust_claim NUMERIC DEFAULT 0,
    ncv_act NUMERIC DEFAULT 0,
    ncv_claim NUMERIC DEFAULT 0,
    grade_down_act NUMERIC DEFAULT 0,
    grade_down_claim NUMERIC DEFAULT 0,
    final_receipt_wt NUMERIC DEFAULT 0,
    settlement_moisture NUMERIC DEFAULT 0,
    settlement_grade_down NUMERIC DEFAULT 0,
    settlement_dust NUMERIC DEFAULT 0,
    settlement_ncv NUMERIC DEFAULT 0,
    ropes_weight NUMERIC DEFAULT 0,
    ropes_tot_wt_grd NUMERIC DEFAULT 0,
    ropes_grade TEXT,
    chotta_weight NUMERIC DEFAULT 0,
    chotta_tot_wt_grd NUMERIC DEFAULT 0,
    chotta_grade TEXT,
    tolerable TEXT,
    row_remarks TEXT,
    jqi_remarks TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS mill_inspection_master (
    mr_no TEXT PRIMARY KEY,
    mr_date DATE,
    date DATE,
    arrival_no TEXT,
    arrival_date DATE,
    po_no TEXT,
    po_date DATE,
    broker_name TEXT,
    supplier_name TEXT,
    arrival_area_code TEXT,
    arrival_area_name TEXT,
    arrival_area TEXT,
    grid_details JSONB,
    actual_moisture NUMERIC,
    claim_moisture NUMERIC,
    actual_dust NUMERIC,
    claim_dust NUMERIC,
    actual_ncv NUMERIC,
    claim_ncv NUMERIC,
    status TEXT DEFAULT 'Completed',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    lorry_number TEXT,
    arival_apmc_fees NUMERIC DEFAULT 0
);

CREATE TABLE IF NOT EXISTS mill_inspection_detail (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mr_no TEXT,
    srl_no INTEGER,
    arrival_grade TEXT,
    stock_grade_code TEXT,
    stock_grade_name TEXT,
    area TEXT,
    agency TEXT,
    marka TEXT,
    marks TEXT,
    crop_year TEXT,
    lot TEXT,
    quantity NUMERIC DEFAULT 0,
    unit TEXT DEFAULT 'BALES',
    challan_gross_wt NUMERIC DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS lorry_weighments (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    lorry_no TEXT NOT NULL,
    gross_weight NUMERIC(15,3),
    tare_weight NUMERIC(15,3),
    net_weight NUMERIC(15,3),
    weighment_date DATE,
    weighbridge_slip_no TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS payment_master (
    payment_id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    payment_no TEXT,
    payment_date DATE,
    supplier TEXT,
    po_no TEXT,
    mr_no TEXT,
    gross_amount NUMERIC(15,2),
    total_deductions NUMERIC(15,2),
    net_amount NUMERIC(15,2),
    payment_mode TEXT,
    cheque_rtgs_no TEXT,
    status TEXT DEFAULT 'processed',
    part_payment NUMERIC(15,2),
    advance_adjusted NUMERIC(15,2),
    tds_deducted NUMERIC(15,2),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS payment_details (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    payment_id TEXT,
    particulars TEXT,
    amount NUMERIC(15,2),
    deduction_type TEXT,
    rate NUMERIC(15,2),
    quantity NUMERIC(15,2),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS imap_emails (
    id TEXT PRIMARY KEY,
    subject TEXT,
    sender_name TEXT,
    sender_email TEXT,
    date TIMESTAMP WITH TIME ZONE,
    snippet TEXT,
    body TEXT,
    html TEXT,
    attachments JSONB,
    unread BOOLEAN DEFAULT TRUE,
    starred BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS material_mismatch (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    mr_no TEXT,
    po_no TEXT,
    lorry_no TEXT,
    mismatch_type TEXT,
    description TEXT,
    status TEXT DEFAULT 'Pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Stored Procedures
CREATE OR REPLACE FUNCTION exec_sql(query text)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  EXECUTE query;
END;
$$;

CREATE OR REPLACE FUNCTION exec_sql_return(query text)
RETURNS SETOF jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    r record;
BEGIN
    FOR r IN EXECUTE query LOOP
        RETURN NEXT to_jsonb(r);
    END LOOP;
END;
$$;
